export const ROLES = {
  USER: 'USER',
  TECHNICIAN: 'TECHNICIAN',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const AUTHENTICATED_ROLES = [
  ROLES.USER,
  ROLES.TECHNICIAN,
  ROLES.ADMIN,
  ROLES.SUPER_ADMIN,
];

export const ADMIN_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN];
